# Generated by Django 5.2.4 on 2025-07-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rate_per_unit',
            new_name='rate',
        ),
    ]
