# Generated by Django 5.2.4 on 2025-07-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0002_rename_rate_per_unit_product_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rate',
            new_name='rate_per_unit',
        ),
    ]
