# Generated by Django 5.2.4 on 2025-07-24 12:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0009_dailywork_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
        migrations.AddField(
            model_name='product',
            name='customer_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price charged to customer per piece', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tailor_payment_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid to tailor per piece', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('jazzCash', 'Jazz Cash'), ('easyPaisa', 'Easy Paisa'), ('other', 'Other')], max_length=20),
        ),
    ]
