# Generated by Django 5.2.4 on 2025-07-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0010_remove_product_rate_product_customer_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='dailywork',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='assigned_tailor',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_price',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='is_order_work',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='quality_rating',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='work_type',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
