# Generated by Django 5.2.4 on 2025-07-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0011_remove_order_customer_remove_dailywork_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='customer_name',
            field=models.CharField(default='Unknown Customer', max_length=255),
        ),
    ]
