# Generated by Django 5.2.4 on 2025-07-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0003_rename_rate_product_rate_per_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rate_per_unit',
            new_name='rate',
        ),
    ]
