# Generated by Django 5.2.4 on 2025-07-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0004_rename_rate_per_unit_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='date',
            field=models.DateField(),
        ),
    ]
