# Generated by Django 5.2.4 on 2025-07-24 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0008_alter_customer_options_alter_dailywork_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_work_records', to='wages.customer'),
        ),
    ]
